# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.7
  - 3.6.11

before_install: python -m pip install --upgrade pip
install: pip install tox-travis

# Command to run tests
script: tox

before_deploy: pip install poetry
deploy:
  skip_cleanup: true
  provider: script
  script:
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - poetry config http-basic.pypi "__token__" "${POETRY_HTTP_BASIC_TESTPYPI_PASSWORD}"
    - poetry publish -r testpypi --build
  on:
    tags: true
    repo: AdemFr/pipelog
    python: 3.7
    branch: master
