# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.7
  - 3.6.11

before_install: python -m pip install --upgrade pip
install: pip install -U tox-travis

# Command to run tests
script: tox

# TODO $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ademfr
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: ademfr/pipelog
    python: 3.7
